# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false

# Project
mod_id = polytone
mod_name = Polytone
mod_version = 1.21.11-5.9.3
mod_author = MehVahdJukaar
mod_description = Your Resource Packs Best Friend
mod_license = Supplementaries Team License v.1.5
mod_authors = MehVahdJukaar, Plantkillable
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/polytone
mod_credits = MehVahdJukaar, Murao.kun, gayaslily, Plantkillable
mod_github = https://github.com/MehVahdJukaar/polytone


release_type = release
maven_group = net.mehvahdjukaar


# Publishing
repository = mehvahdjukaar/polytone
modrinth_project_id =  polytone
curseforge_project_id = 958094

mc_version = 1.21.11


parchment_mappings_version = 2025.12.20
neoforge_version = 21.11.38-beta

fabric_api_version = 0.141.1+1.21.11
fabric_loader_version = 0.19.2




mvel_version = 2.5.2.Final
exp4j_version = 0.4.8
candlelight_version = 1.0.3
flatlaf_version = 3.5.4
rsyntaxtextarea_version = 3.5.4

