package net.mehvahdjukaar.polytone.mixins;

import com.llamalad7.mixinextras.injector.wrapoperation.Operation;
import com.llamalad7.mixinextras.injector.wrapoperation.WrapOperation;
import net.mehvahdjukaar.polytone.Polytone;
import net.minecraft.client.renderer.block.model.BlockModel;
import net.minecraft.client.resources.model.ModelBakery;
import net.minecraft.client.resources.model.ModelResourceLocation;
import net.minecraft.client.resources.model.UnbakedModel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.util.profiling.ProfilerFiller;
import org.spongepowered.asm.mixin.Final;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Mutable;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

import java.util.HashMap;
import java.util.Map;

@Mixin(ModelBakery.class)
public class ModelBakeryMixin {

    @Shadow @Final private Map<ModelResourceLocation, UnbakedModel> topModels;

    @Shadow @Final private Map<ResourceLocation, UnbakedModel> unbakedModels;

    @Inject(method = "<init>", at = @At(value = "TAIL"))
    private void polytone$addGeneratedCustomItemModels(Map map, Map map2, UnbakedModel unbakedModel, CallbackInfo ci) {
        Map<ResourceLocation, BlockModel> autoGeneratedModels = Polytone.ITEM_MODELS.createAutoGeneratedModels();

        if (!autoGeneratedModels.isEmpty()) {
            // TODO probably worng
            this.unbakedModels.putAll(autoGeneratedModels);
            autoGeneratedModels.forEach((key, value) -> {
                String p = Polytone.isForge ? "standalone" : "fabric_resource";
                this.topModels.put(new ModelResourceLocation(key, p), value);
            });
        }
    }
}
