package net.mehvahdjukaar.polytone.mixins;

import net.minecraft.client.resources.model.ModelBakery;
import org.spongepowered.asm.mixin.Mixin;

@Mixin(ModelBakery.class)
public class ModelBakeryMixin {

    /*
    @Shadow @Final private Map<ModelResourceLocation, UnbakedModel> topModels;

    @Shadow @Final private Map<ResourceLocation, UnbakedModel> unbakedModels;

    @Inject(method = "<init>", at = @At(value = "TAIL"))
    private void polytone$addGeneratedCustomItemModels(Map map, Map map2, UnbakedModel unbakedModel, CallbackInfo ci) {
        Map<ResourceLocation, BlockModel> autoGeneratedModels = Polytone.ITEM_MODELS.createAutoGeneratedModels();

        if (!autoGeneratedModels.isEmpty()) {
            // TODO probably worng
            this.unbakedModels.putAll(autoGeneratedModels);
            autoGeneratedModels.forEach((key, value) -> {
                String p = Polytone.isForge ? "standalone" : "fabric_resource";
                this.topModels.put(new ModelResourceLocation(key, p), value);
            });
        }
    }*/
}
