architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}


publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "4000"

}


dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    //  modApi "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}:fabric-convention-tags-v2"

    compileOnly "net.mehvahdjukaar:candlelight:${candle_version}"
    implementation "net.objecthunter:exp4j:${exp4j_version}"
    implementation "org.mvel:mvel2:${mvel_version}"

    modCompileOnly "curse.maven:serene-seasons-291874:6182596"
    modCompileOnly "curse.maven:fabric-seasons-413523:5789846"
    modCompileOnly("curse.maven:irisshaders-455508:6369436")
    modCompileOnly("curse.maven:sodium-394468:7366772")
    modCompileOnly("curse.maven:entity-model-features-844662:7400754")
    modCompileOnly("curse.maven:entity-texture-features-fabric-568563:7392425")

    implementation "org.ow2.asm:asm:9.5"
    implementation "org.ow2.asm:asm-commons:9.5"
}

