package net.mehvahdjukaar.polytone.item;

import net.minecraft.resources.Identifier;

public record AutoGeneratedModel(Identifier modelLocation, Identifier texturePath) {

    public static AutoGeneratedModel ofCIM(Identifier cimPath) {
        Identifier modelLocation = cimPath.withPrefix("item/polytone_generated_");
        return new AutoGeneratedModel(modelLocation, cimPath.withPrefix("polytone/custom_item_models/"));
    }
}
