package net.mehvahdjukaar.polytone.item;

import net.minecraft.resources.ResourceLocation;

public record AutoGeneratedModel(ResourceLocation modelPath, ResourceLocation texturePath) {
    public static AutoGeneratedModel createDefault(ResourceLocation location) {
        return new AutoGeneratedModel(location, location);
    }
}
