package net.mehvahdjukaar.polytone.item;

import com.google.gson.JsonElement;
import com.mojang.serialization.DynamicOps;
import com.mojang.serialization.JsonOps;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import net.mehvahdjukaar.polytone.Polytone;
import net.mehvahdjukaar.polytone.utils.JsonImgPartialReloader;
import net.mehvahdjukaar.polytone.utils.PartialReloader;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.renderer.block.model.BlockModel;
import net.minecraft.client.resources.model.BakedModel;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import org.apache.commons.lang3.time.StopWatch;
import org.jetbrains.annotations.Nullable;

import java.util.*;

public class CustomItemModelsManager extends PartialReloader<Object> {


    private final Map<Item, ItemModelOverrideList> itemModels = new Object2ObjectOpenHashMap<>();
    private final Set<ResourceLocation> extraModels = new HashSet<>();
    private final Set<AutoGeneratedModel> autoGeneratedModels = new HashSet<>();

    public CustomItemModelsManager() {
        super("custom_item_models");

    }

    @Override
    protected Object prepare(ResourceManager resourceManager) {
        return new Object();
    }

    @Override
    protected void reset() {

    }

    @Override
    protected void process(Object obj, DynamicOps<JsonElement> ops) {

    }

    public void earlyProcess(ResourceManager resourceManager) {
        this.itemModels.clear();
        this.extraModels.clear();
        this.autoGeneratedModels.clear();

        StopWatch stopWatch = StopWatch.createStarted();
        var jsons = this.getJsonsInDirectories(resourceManager);

        for (var v : jsons.entrySet()) {
            JsonElement json = v.getValue();
            ResourceLocation location = v.getKey();

            StandaloneItemModelOverride modelOverride = StandaloneItemModelOverride.CODEC.decode(JsonOps.INSTANCE, json)
                    .getOrThrow(errorMsg -> new IllegalStateException("Could not decode Custom Item Model with json id " + location + "\n error: " + errorMsg))
                    .getFirst();

            if (modelOverride != null) {
                // merge
                // load model

                if (modelOverride.isAutoModel()) {
                    AutoGeneratedModel generated = AutoGeneratedModel.ofCIM(location);
                    this.autoGeneratedModels.add(generated);
                    modelOverride.setModel(generated.modelLocation());
                }
                this.extraModels.add(modelOverride.model());

                this.itemModels.computeIfAbsent(modelOverride.getTarget(), a -> new ItemModelOverrideList())
                        .add(modelOverride);
            }
        }

        Polytone.LOGGER.info("Loaded {} Custom Item Models jsons in {}", jsons.size(), stopWatch);
    }

    @Override
    protected void apply() {
        super.apply();
        int allModels = 0;
        for (var list : this.itemModels.values()) {
            allModels += list.size();
        }
        Polytone.LOGGER.info("Loaded {} Custom Item Models for {} items", allModels, this.itemModels.size());
    }

    @Nullable
    public BakedModel getOverride(ItemStack itemStack, @Nullable ClientLevel level, @Nullable LivingEntity entity, int seed) {
        //TODO: ad entity and level predicates
        ItemModelOverrideList list = this.itemModels.get(itemStack.getItem());
        if (list == null) return null;
        return list.getModel(itemStack, level, entity, seed);
    }

    public Set<ResourceLocation> getExtraModels() {
        return extraModels;
    }

    public Map<ResourceLocation, BlockModel> createAutoGeneratedModels() {
        Map<ResourceLocation, BlockModel> models = new HashMap<>();
        for (AutoGeneratedModel model : this.autoGeneratedModels) {

            String texturePath = model.texturePath().toString();
            BlockModel unbakedModel = BlockModel.fromString(
                    String.format("""
                            {
                              "parent": "item/generated",
                              "textures": {
                                "layer0": "%s"
                              }
                            }
                            """, texturePath));

            models.put(model.modelLocation(), unbakedModel);
        }
        return models;
    }

    public void addModel(Item target, List<ItemModelOverride> overrides) {
        this.itemModels.computeIfAbsent(target, a -> new ItemModelOverrideList())
                .addAll(overrides);
        this.extraModels.addAll(overrides.stream().map(ItemModelOverride::model).toList());
    }
}
