modLoader = "javafml"
loaderVersion = "*". i

license = "${mod_license}"
issueTrackerURL = "${mod_github}/issues"

[[mixins]]
    config = "${mod_id}.mixins.json"
[[mixins]]
    config = "${mod_id}-common.mixins.json"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    logoFile = "icon.png"
    authors = "${mod_authors}"
    credits = "${mod_credits}"
    description = '''${mod_description}'''
    modUrl = "${mod_homepage}"
    itemIcon = "minecraft:brush"

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "*"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}]"
    ordering = "NONE"
    side = "CLIENT"
