package net.mehvahdjukaar.polytone.content.item;

import com.google.gson.JsonElement;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import net.mehvahdjukaar.polytone.misc.reloader.JsonPartialReloader;
import net.minecraft.client.renderer.block.model.BlockModel;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.PreparableReloadListener;
import net.minecraft.world.item.Item;

import java.io.StringReader;
import java.util.*;

public class CustomItemModelsManager extends JsonPartialReloader {


    private final Map<Item, ItemModelOverrideList> itemModels = new Object2ObjectOpenHashMap<>();
    private final Set<AutoGeneratedModel> autoGeneratedModels = new HashSet<>();

    private final Map<Item, List<ItemModelOverride>> itemModifiersModels = new HashMap<>();

    public CustomItemModelsManager() {
        super("custom_item_models");

    }

    @Override
    protected void resetWithLevel(boolean logOff) {
        this.itemModels.clear();
        this.autoGeneratedModels.clear();
    }

    @Override
    protected void earlyProcess(PreparableReloadListener.SharedState sharedState) {
        var resourceManager = sharedState.resourceManager();
        var jsons = getJsonsInDirectories(resourceManager);
        /* //TODO: add back someday
        for (var e : Parsed.batchParseOnlyEnabled(jsons, StandaloneItemModelOverride.CODEC_MODEL_ONLY,
                JsonOps.INSTANCE, "custom item model")) {
            var partial = e.getValue();
            if (!partial.autoModel()) {
                Polytone.addCustomModel(partial.model());
            }
        }*/
    }

    @Override
    protected void parseWithLevel(Map<ResourceLocation, JsonElement> jsons, RegistryOps<JsonElement> ops, HolderLookup.Provider access) {
        this.itemModels.clear();
        this.autoGeneratedModels.clear();
        // we must early load item modifiers aswell here...

        // load item modifiers ones
        for (var l : this.itemModifiersModels.entrySet()) {
            var target = l.getKey();
            var overrides = l.getValue();
            //this.itemModels.computeIfAbsent(target, a -> new ItemModelOverrideList())
            //        .addAll(overrides);
        }
        this.itemModifiersModels.clear();

        /*
        for (var v : Parsed.batchParseOnlyEnabled(jsons, StandaloneItemModelOverride.CODEC,
                ops, "custom item model")) {
            ResourceLocation location = v.getKey();
            StandaloneItemModelOverride modelOverride = v.getValue();

            // merge
            // load model
            if (modelOverride.isAutoModel()) {
                AutoGeneratedModel generated = AutoGeneratedModel.ofCIM(location);
                this.autoGeneratedModels.add(generated);
                modelOverride.setModel(ModelResHelper.of(generated.modelLocation()));
            }

            this.itemModels.computeIfAbsent(modelOverride.getTarget(), a -> new ItemModelOverrideList())
                    .add(modelOverride);
        }*/
    }

    @Override
    protected void applyWithLevel(HolderLookup.Provider access, boolean isLogIn) {
        for (var list : this.itemModels.values()) {
          //  list.populateModels(access);
        }
        int allModels = 0;
        for (var list : this.itemModels.values()) {
           // allModels += list.size();
        }
      //  Polytone.LOGGER.info("Loaded {} Custom Item Models for {} items", allModels, this.itemModels.size());
    }

    /*
    @Nullable
    public BakedModel getOverride(ItemStack itemStack, @Nullable Level level, @Nullable LivingEntity entity, int seed) {
        if (level == null) return null;
        ItemModelOverrideList list = this.itemModels.get(itemStack.getItem());
        if (list == null) return null;
        return list.getModel(itemStack, level, entity, seed);
    }*/

    public Map<ResourceLocation, BlockModel> createAutoGeneratedModels() {
        Map<ResourceLocation, BlockModel> models = new HashMap<>();
        for (AutoGeneratedModel model : this.autoGeneratedModels) {

            String texturePath = model.texturePath().toString();
            try (StringReader reader = new StringReader(String.format("""
                            {
                              "parent": "item/generated",
                              "textures": {
                                "layer0": "%s"
                              }
                            }
                            """, texturePath))) {
                BlockModel unbakedModel = BlockModel.fromStream(reader);
                models.put(model.modelLocation(), unbakedModel);
            }
        }
        return models;
    }

    public void addModelFromModifier(Item item, List<ItemModelOverride> itemModelOverrides) {
        itemModifiersModels.computeIfAbsent(item, a -> new ArrayList<>()).addAll(itemModelOverrides);
    }
}
