package net.mehvahdjukaar.polytone.content.item;

import com.google.gson.JsonElement;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import net.mehvahdjukaar.polytone.common.reloader.ContentManager;
import net.mehvahdjukaar.polytone.common.struc.AssetsFiles;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.RegistryOps;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.PreparableReloadListener;
import net.minecraft.world.item.Item;

import java.util.*;

public class CustomItemModelsManager extends ContentManager<Void> {


    private final Map<Item, ItemModelOverrideList> itemModels = new Object2ObjectOpenHashMap<>();
    private final Set<AutoGeneratedModel> autoGeneratedModels = new HashSet<>();

    private final Map<Item, List<ItemModelOverride>> itemModifiersModels = new HashMap<>();

    public CustomItemModelsManager() {
        super("Custom item model");

    }

    @Override
    protected void resetWithLevel(boolean logOff) {
        this.itemModels.clear();
        this.autoGeneratedModels.clear();
    }

    @Override
    protected void earlyProcess(PreparableReloadListener.SharedState sharedState) {
        var resourceManager = sharedState.resourceManager();
        var jsons = getJsonsInDirectories(resourceManager);
        /* //TODO: add back someday
        for (var e : Parsed.batchParseOnlyEnabled(jsons, StandaloneItemModelOverride.CODEC_MODEL_ONLY,
                JsonOps.INSTANCE, "custom item model")) {
            var partial = e.getValue();
            if (!partial.autoModel()) {
                Polytone.addCustomModel(partial.model());
            }
        }*/
    }

    @Override
    protected void parseWithLevel(AssetsFiles resources, RegistryOps<JsonElement> ops, HolderLookup.Provider access) {
        Map<Identifier, JsonElement> jsons = resources.jsons();
        this.itemModels.clear();
        this.autoGeneratedModels.clear();
        // we must early load item modifiers aswell here...

        // load item modifiers ones
        for (var l : this.itemModifiersModels.entrySet()) {
            var target = l.getKey();
            var overrides = l.getValue();
            //this.itemModels.computeIfAbsent(target, a -> new ItemModelOverrideList())
            //        .addAll(overrides);
        }
        this.itemModifiersModels.clear();

        /*
        for (var v : Parsed.batchParseOnlyEnabled(jsons, StandaloneItemModelOverride.CODEC,
                ops, "custom item model")) {
            Identifier location = v.getKey();
            StandaloneItemModelOverride modelOverride = v.getValue();

            // merge
            // load model
            if (modelOverride.isAutoModel()) {
                AutoGeneratedModel generated = AutoGeneratedModel.ofCIM(location);
                this.autoGeneratedModels.add(generated);
                modelOverride.setModel(ModelResHelper.of(generated.modelLocation()));
            }

            this.itemModels.computeIfAbsent(modelOverride.getTarget(), a -> new ItemModelOverrideList())
                    .add(modelOverride);
        }*/
    }

    @Override
    protected void applyWithLevel(HolderLookup.Provider access, boolean isLogIn) {
        for (var list : this.itemModels.values()) {
          //  list.populateModels(access);
        }
        int allModels = 0;
        for (var list : this.itemModels.values()) {
           // allModels += list.size();
        }
      //  Polytone.LOGGER.info("Loaded {} Custom Item Models for {} items", allModels, this.itemModels.size());
    }

    /*
    @Nullable
    public BakedModel getOverride(ItemStack itemStack, @Nullable Level level, @Nullable LivingEntity entity, int seed) {
        if (level == null) return null;
        ItemModelOverrideList list = this.itemModels.get(itemStack.getItem());
        if (list == null) return null;
        return list.getModel(itemStack, level, entity, seed);
    }*/

    public Map<Identifier, Object> createAutoGeneratedModels() {
        // TODO: BlockModel.fromStream was removed in 26.1; model loading pipeline changed
        return new HashMap<>();
    }

    public void addModelFromModifier(Item item, List<ItemModelOverride> itemModelOverrides) {
        itemModifiersModels.computeIfAbsent(item, a -> new ArrayList<>()).addAll(itemModelOverrides);
    }
}
